title: "Text AI 강의 노트"
description: "고려사이버대학교 자연어처리(BERT, 텍스트 마이닝) 강의 노트"
author: "Hojin"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# Navigation
nav_sort: 'priorities'

# Build Settings
destination: docs
source: src
url: "https://text.ai.jiny.dev"
baseurl: ""
markdown: kramdown
kramdown:
  math_engine: mathjax

defaults:
  - scope:
      path: ""
    values:
      layout: "docs"

# Sass 설정
sass:
  load_paths:
    - _sass

# GitHub Pages 호환성을 위한 설정
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - .git/
  - README.md
  - package.json
  - package-lock.json
